name: Backend Multi-Stage Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Stage for deployment
        required: true
        options:
          - dev
          - stg
          - prd

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [auth, integration, members, parkings, payments]

    steps:
      # コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 環境変数の設定
      - name: Resolve AWS Account ID
        id: resolve_ids
        run: |
          if [ "${{ inputs.environment }}" == "dev" ]; then
            case ${{ matrix.account }} in
              auth)         echo "ACCOUNT=1111" >> $GITHUB_ENV ;;
              integration)  echo "ACCOUNT=2222" >> $GITHUB_ENV ;;
              members)      echo "ACCOUNT=3333" >> $GITHUB_ENV ;;
              parkings)     echo "ACCOUNT=4444" >> $GITHUB_ENV ;;
              payments)     echo "ACCOUNT=5555" >> $GITHUB_ENV ;;
            esac
          elif [ "${{ inputs.environment }}" == "stg" ]; then
            case ${{ matrix.account }} in
              auth)         echo "ACCOUNT=" >> $GITHUB_ENV ;;
              integration)  echo "ACCOUNT=" >> $GITHUB_ENV ;;
              members)      echo "ACCOUNT=" >> $GITHUB_ENV ;;
              parkings)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
              payments)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
            esac
          elif [ "${{ inputs.environment }}" == "prd" ]; then
            case ${{ matrix.account }} in
              auth)         echo "ACCOUNT=" >> $GITHUB_ENV ;;
              integration)  echo "ACCOUNT=" >> $GITHUB_ENV ;;
              members)      echo "ACCOUNT=" >> $GITHUB_ENV ;;
              parkings)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
              payments)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
            esac
          fi

          # 解決したアカウントIDを後続ステップで使えるように出力
          echo ${{ env.ACCOUNT }}

      # - name: Setup credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ env.ROLE_ARN }}
      #     aws-region: ${{ env.REGION }}

      # ブランチ作成時にワークフローが実行されるため、コメントアウト
      # - name: Build and deploy SAM application
      #   run: |
      #     sam build --config-env ${{ env.STAGE }}
      #     sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env ${{ env.STAGE }}
