name: Backend Multi-Stage Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Stage for deployment
        required: true
        options:
          - dev
          - stg
          - prd

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: [auth, integration, members, parkings, payments]

    steps:
      # コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 環境変数の設定
      - name: Resolve AWS Account ID
        id: resolve_ids
        run: |
          if [ "${{ inputs.environment }}" == "dev" ]; then
            case ${{ matrix.account }} in
              auth)         echo "ACCOUNT=121431344263" >> $GITHUB_ENV ;;
              integration)  echo "ACCOUNT=008700326646" >> $GITHUB_ENV ;;
              members)      echo "ACCOUNT=352126234225" >> $GITHUB_ENV ;;
              parkings)     echo "ACCOUNT=077239123954" >> $GITHUB_ENV ;;
              payments)     echo "ACCOUNT=915515002700" >> $GITHUB_ENV ;;
            esac
          elif [ "${{ inputs.environment }}" == "stg" ]; then
            case ${{ matrix.account }} in
              auth)         echo "ACCOUNT=" >> $GITHUB_ENV ;;
              integration)  echo "ACCOUNT=" >> $GITHUB_ENV ;;
              members)      echo "ACCOUNT=" >> $GITHUB_ENV ;;
              parkings)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
              payments)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
            esac
          elif [ "${{ inputs.environment }}" == "prd" ]; then
            case ${{ matrix.account }} in
              auth)         echo "ACCOUNT=" >> $GITHUB_ENV ;;
              integration)  echo "ACCOUNT=" >> $GITHUB_ENV ;;
              members)      echo "ACCOUNT=" >> $GITHUB_ENV ;;
              parkings)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
              payments)     echo "ACCOUNT=" >> $GITHUB_ENV ;;
            esac
          fi
          echo 'PHASE=${{ inputs.environment }}' >> $GITHUB_ENV 
          echo 'REGION=ap-northeast-1' >> $GITHUB_ENV
          echo 'ROLE_ARN=arn:aws:iam::077239123954:role/npc-parkings-${{ inputs.environment }}-role-github-actions' >> $GITHUB_ENV

      - name: Setup credentials
        run: |
          echo "The account ID is ${{ env.ACCOUNT }}"
          echo "The ROLE_ARN is ${{ env.ROLE_ARN }}"
        # uses: aws-actions/configure-aws-credentials@v4
        # with:
        #   role-to-assume: ${{ env.ROLE_ARN }}
        #   aws-region: ${{ env.REGION }}

      # ブランチ作成時にワークフローが実行されるため、コメントアウト
      # - name: Build and deploy SAM application
      #   run: |
      #     sam build --config-env ${{ env.STAGE }}
      #     sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env ${{ env.STAGE }}
