name: Prevent invalid merges to develop

on:
  pull_request:
    branches:
      - develop

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the source branch is allowed
        run: |
          echo "Source: ${{ github.head_ref }}"
          if [[ ! "${{ github.head_ref }}" =~ ^(feature/|hotfix/) ]]; then
            echo "Only PRs from 'feature/ or hotfix/' branch can be merged into 'develop'."
            exit 1
          fi
