name: Prevent invalid merges to staging

on:
  pull_request:
    branches:
      - staging

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the source branch is allowed
        run: |
          echo "Source: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "develop" || ! "${{ github.head_ref }}" =~ ^hotfix/ ]]; then
            echo "Only PRs from 'develop or hotfix/' branch can be merged into 'staging'."
            exit 1
          fi
