name: Prevent invalid merges to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the source branch is allowed
        run: |
          echo "Source: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "staging" || ! "${{ github.head_ref }}" =~ ^hotfix/ ]]; then
            echo "Only PRs from 'staging or hotfix/' branch can be merged into 'main'."
            exit 1
          fi
