name: Run Tests

on:
  pull_request:
    branches:
      - develop
      - staging
      - main
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Python をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 依存関係をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # テストを実行（カバレッジを測定）
      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pip install -r backend/tests/requirements.txt
          pytest --cov=backend --cov-fail-under=75 backend/tests
